### ISSUE TITLE
Informe 1

### ISSUE THREAD

**Issue by gorojas** [ggonzalezo/i-fila#1]
1.-
 Descripción del problema que se quiere resolver
- Concepto general del sistema y alcance de la solución

**Comment by gorojas** [comment]
1. INTRODUCCIÓN
   1.1.  Descripción General del Problema

CENCOSUD S.A es una multinacional chilena, presente en distintas parte de Latinoamérica, la cual se dedica principalmente al comercio minorista, teniendo entre sus tiendas a importantes supermercados y locales de venta por departamento, entre sus principales empresas encontramos a Jumbo y Paris, sin embargo también se ha integrado horizontalmente ingresando en la industria financiera, seguros, entre otros. Es importante destacar que para efectos de este trabajo, nos enfocaremos en la unidad de negocio de los supermercados Jumbo.
//Supermercados Jumbo cuenta con TIENDAS… CANTIDAS DE TRABAJADORES… ETC.
En la empresa se ha identificado un problema y corresponde a la gestión de filas en la zona de fiambrerías y carnicerías de todas las salas de ventas de los supermercados. El problema consiste en una excesiva acumulación en las horas punta, tanto de carros como de personas en el pasillo donde se encuentran ubicada la zona para comprar tanto productos de rotisería como carnes, provocando desorden en el lugar y obstruyendo el paso a otros clientes, disminuyendo significativamente la calidad de servicio entregada por el supermercado.
Dado lo anterior, es que para el mejoramiento de la calidad de servicio se propone la instauración de un novedoso sistema de información que permita aumentar la calidad de servicio, mediante la descongestión de esta zona, incentivando también la compra en otras zonas del supermercado mientras realiza la espera de su turno.

**Comment by ggonzalezo** [comment]
https://docs.google.com/presentation/d/1p8YBjR68ZbPCfJl7T0rncgbd17YPqN-YcMQ7su82aDE/edit?usp=sharing

Presentación de hoy.
